import Head from 'next/head'
import Header from '../components/lookbook/header'
import ScrollToTop from '../components/ScrollToTop'
import Lookbook from '../components/lookbook/Lookbook'
import LookbookAll from '../components/lookbook/LookbookAll'
import Footer from '../components/Footer'


const lookbook = () => {
  return (
    <div>
      <Head>
        <title>Lookbook | Sense Hair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ScrollToTop />
      <Lookbook />
      <LookbookAll />
      <Footer />
    </div>
  )
}

export default lookbook
