import Head from 'next/head'
import Footer from '../components/Footer'
import MainMenu from '../components/MainMenu'
import ScrollToTop from '../components/ScrollToTop'
import PriceModal from '../components/services/PriceModal'
import Prices from '../components/services/Prices'
import ServicesText from '../components/services/ServicesText'

const services = () => {
  return (
    <div>
      <Head>
        <title>Services | Sense Hair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainMenu />
      <ScrollToTop />
      <ServicesText />
      <Prices />
      <Footer />
      <PriceModal />

    </div>
  )
}

export default services
